### ISSUE TITLE
psi_common_axi_slave_ipif64_tb does not compile with GHDL

### ISSUE THREAD

**Issue by obruendl** [paulscherrerinstitute/psi_common#19]
The GHDL regression test is broken becasue _psi_common_axi_slave_ipif64_tb _ does not compile. This should be fixed, otherwise the open source simulator is no more supported by the PSI libraries which would be a pitty. Open source libraries should work with open source tools.

**Comment by obruendl** [comment]
BTW: The issue was found on the develop branch.

**Comment by BenoitStef** [comment]
The ipif64 isn't an issue on master and now on develop so merging to develop resolved the problem I guess.

**Comment by obruendl** [comment]
I tested with release 2.13.0 and still I see the same errors when running the regression test.

Did you run the regression test with GHDL or only with Modelsim? Which GHDL version did you use?

attached you can find a screenshot containing the errors as well as the GHDL version I use.

![image](https://user-images.githubusercontent.com/12606595/89636511-05681000-d8a9-11ea-9fdf-e1c92135caa7.png)

**Comment by BenoitStef** [comment]
![ghdl_compile](https://user-images.githubusercontent.com/45063918/90337240-71512380-dfe1-11ea-8933-45c5686bc188.png)

**Comment by BenoitStef** [comment]
![image](https://user-images.githubusercontent.com/45063918/90337272-b6755580-dfe1-11ea-8694-6c19c077c4f7.png)

**Comment by BenoitStef** [comment]
![image](https://user-images.githubusercontent.com/45063918/90337297-d86ed800-dfe1-11ea-90a6-d02aededc7c0.png)

**Comment by BenoitStef** [comment]
From my side it compiles without error. Here above you have screenshots with compilation, simulation results and GHDL version. I launched the compile/sim from last master branch. I will check with other coworker if they found an issue and come back to you if it is the case

**Comment by obruendl** [comment]
My bad. I missed the fact that a newer version of psi_tb is required. Sorry
