### ISSUE TITLE
RamStyle_g = "ultra"

### ISSUE THREAD

**Issue by obruendl** [paulscherrerinstitute/psi_common#22]
Wherever RAM can be mapped into UltraRAMs (for UltraScale+ devices), the RamStyle_g = "ultra" generic can be used. I checked this and it works without any changes to the code.

The only thing left would be updating the documentation. When doing so, it would be important keeping in mind the limitations of UltraRAM (same clock for both ports, only one write and one read port - not two read/write ports). One would have to go through all blocks and check where UltraRAM implementation is possible.

I already know that it is possible for:
* psi\_common\_sync\_fifo

**Comment by obruendl** [comment]
@BenoitStef 
Any update on this?

**Comment by BenoitStef** [comment]
nope I didn't check as I am not using often vivado so far, what I could do then is simply update but as you said I should chek if with vivado all block can be used carefully with this attribute ^^ I will try to have a look
