### ISSUE TITLE
port naming for psi_common_min_max_mean

### ISSUE THREAD

**Issue by obruendl** [paulscherrerinstitute/psi_common#35]
@BenoitStef 

Would it be possible to use "sum" instead of "mean" for port and signal naming in psi_commoon_min_max_mean? As far as I see it does not calculate the mean but only the sum. If I am correct with this interpretation, I think the port name "mean" is misleading.

**Comment by BenoitStef** [comment]
Hi Oliver yes it's possible I will do this now
