### ISSUE TITLE
psi_common_trigger_generator review

### ISSUE THREAD

**Issue by obruendl** [paulscherrerinstitute/psi_common#5]
I did a review of the psi_common_trigger_generator. 

Review comments can be found in the code attached (marked with *[COMMENT OBRU]*).

Generally it looks like there is quite a bit of confusion how the two process method works (i.e. when v.xxx and when r.xxx is used). 

To me it also looks like this element takes quite some assumptions that are not true in general.

[psi_common_trigger_generator.txt](https://github.com/paulscherrerinstitute/psi_common/files/4266034/psi_common_trigger_generator.txt)

**Comment by BenoitStef** [comment]
I close this issue since Daniele is working on it and will make a pull request once the block is ready to be reviewed

**Comment by obruendl** [comment]
OK. THX.
