### ISSUE TITLE
Refactoring breaks compatibility

### ISSUE THREAD

**Issue by obruendl** [paulscherrerinstitute/psi_common#55]
I have seen that there was a major refacting regarding function names in. I detected the function *ShiftLeft()* in *psi_common_logic_pkg* being renamed to *shiftleft()*.

I see a problem with this. First the refactoring was not propagated to *psi_fix* (*psi_fix_pkg* still used *ShiftLeft*). So the two libraries now became inconsistent.

Do you see this at your end as well or do I overlook something?

I suggest ensuring compatibility.

**Comment by BenoitStef** [comment]
Could you please indicate lines of code because on both master we do not see the issue.

**Comment by PCSerra** [comment]
This could be due to the versions selected in psi_fpga_all:
[https://github.com/paulscherrerinstitute/psi_fpga_all/issues/9](https://github.com/paulscherrerinstitute/psi_fpga_all/issues/9)
