### ISSUE TITLE
psi_common_watchdog_review

### ISSUE THREAD

**Issue by obruendl** [paulscherrerinstitute/psi_common#6]
I reviewed the watchdog.

Code quality looks fine to me. I just found some code that could be simplified, but not functional issues.

Additionally, the question of whether it makes more sense to count "total missing events" or "consecutive missing events" arose for me. Maybe it could also be interesting to have both present (i.e. separate thresholds for error/warning for consectutive misses and total misses)?

[psi_common_watchdog.txt](https://github.com/paulscherrerinstitute/psi_common/files/4266116/psi_common_watchdog.txt)

**Comment by BenoitStef** [comment]
I will take into consideration your comments, I use actually this code several time now in my project to check link and that's why I added to the library, it may be interesting to have both counter as you said I will think about this week and add it to it. 
Thanks

**Comment by BenoitStef** [comment]
Changes have been done accordingly. A new generic is available to select either consecutive missing event either total missing event.
