### ISSUE TITLE
psi_common_async_fifo - Bug for  negative reset polarity 

### ISSUE THREAD

**Issue by obruendl** [paulscherrerinstitute/psi_common#60]
The code here does not work if the reset polarity is negative

![image](https://github.com/paulscherrerinstitute/psi_common/assets/12606595/264fd503-9a15-4f04-acef-0921ec081cd0)

I asked myself if you cover both reset polarities in the regression tests. Probably it would be good.

**Comment by BenoitStef** [comment]
You are correct, I modified the code to work accordingly with a and b polarity, however I figured out that were no tb for the pulse cc. I did quick modif that should be alright but perhaps we should keep consistency and provide tb?

**Comment by BenoitStef** [comment]
bugfix in new release 3.0.1
