### ISSUE TITLE
psi_common_pulse_cc - output reset does not work for low-active reset

### ISSUE THREAD

**Issue by obruendl** [paulscherrerinstitute/psi_common#61]
The line marked in the screenshot below assumes a high-active reset. If the reset is low-active, the reset output is not asserted (stays high).

![image](https://github.com/paulscherrerinstitute/psi_common/assets/12606595/301bce9c-40e4-4502-9332-3879ef927800)

This one is quite severe because the psi_common_pulse_cc is used in many other entities.

**Comment by BenoitStef** [comment]
bugfix in new release 3.0.1
